services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=bangtguh
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
